services:
  listing-service:
    image: pedrovncs/listing-service:latest
    container_name: listing-service-app
    ports:
      - "${LISTING_SERVICE_PORT}:8080"
    environment:
      LISTING_SERVICE_PORT: ${LISTING_SERVICE_PORT}
      LISTING_SERVICE_ELASTIC_URI: ${LISTING_SERVICE_ELASTIC_URI}
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    depends_on:
      listing-elasticsearch:
        condition: service_healthy
    networks:
      - leilao-network

  listing-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    container_name: listing-service-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.http.ssl.enabled=false
    ports:
      - "${LISTING_SERVICE_ELASTIC_PORT}:9200"
    volumes:
      - listing-elastic-data:/usr/share/elasticsearch/data
    networks:
      - leilao-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  listing-elastic-data:

networks:
  leilao-network:
    external: true