spring:
  application:
    name: listing-service

  config:
    import: "optional:file:.env[.properties]"

  elasticsearch:
    uris: ${LISTING_SERVICE_ELASTIC_URI:http://localhost:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: listing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.use.type.headers: false

server:
  port: ${LISTING_SERVICE_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
    prefer-ip-address: true

app:
  kafka-topics:
    connect-topic: "auction_connect.public.auction_lots"